(defun F(l)
    (max (car L) (caddr L))
)

(SETQ F 10)
(SETQ G 'CAR)
(funcall G '(8 11 2 3 7 ))
;(write (funcall G '(8 11 2 3 7 9)))
;(write (G '(8 11 2 3 7 9)))

;(format t "~%")
;(write f)
;(format t "~%")
;(write (function f))
;(format t "~%")
;(write  G)
